### ISSUE TITLE
vue is not update even with valid form

### ISSUE THREAD

**Issue by ScreamZ** [monterail/vuelidate#109] opened 2017-03-26 12:24 UTC
Hey,
just try this one and see that the button is not appearing...

https://www.webpackbin.com/bins/-Kg9XqY8rVXsOoZjrR1t

Any idea ? Vue bug ou binding error ?

Thanks

**Comment by Frizi** [comment] 2017-03-26 20:00
That looks like a bug of tracking `sameAs` dependencies. Probably vuelidate's fault. I'll make a test and fix it.

**Comment by ScreamZ** [comment] 2017-03-26 20:34
@Frizi removed the check with only one password field required, same issue...

**Comment by Frizi** [comment] 2017-03-27 00:52
That's weird. It updates sometimes though. It's unlikely that's on Vue's side, as it's Dep tracking is pretty solid. I'll check that out.

**Comment by ScreamZ** [comment] 2017-03-27 07:45
Take a look on "reactivity caveat"... Looks something like :/

**Comment by arthurkirkosa** [comment] 2017-03-27 08:12
I'm seeing the same thing in the latest version (`0.4.1`) ... the state is not reactive; if I check the component in Dev Tools it updates

**Comment by Frizi** [comment] 2017-03-27 09:40
marking as duplicate of #103, please continue discussion there.

**Closed by Frizi** 2017-03-27 09:40 UTC
Labels: bug
