### ISSUE TITLE
__isVuelidateAsyncVm' of undefined...

### ISSUE THREAD

**Issue by gplume** [monterail/vuelidate#176] opened 2017-08-25 10:54 UTC
Hi there,
I'm stuck to version `0.2.0` !
Version 0.3.0 introduced lots of changes and I have lots of forms tied to vuelidate (thank you for such a great module btw).
If I upgrade to `>= 0.3.0` I have one of my form that throw:

```
[Vue warn]: Error in render function: "TypeError: Cannot read property '__isVuelidateAsyncVm' of undefined"
    at VueComponent.$pending (index.js?112c:249)
    at Watcher.get (vue.runtime.esm.js?ff9b:2877)
    at Watcher.evaluate (vue.runtime.esm.js?ff9b:2984)
    at VueComponent.computedGetter [as $pending] (vue.runtime.esm.js?ff9b:3261)
    at eval (index.js?112c:96)
    at Array.some (<anonymous>)
    at VueComponent.$pending (index.js?112c:95)
    at Watcher.get (vue.runtime.esm.js?ff9b:2877)
    at Watcher.evaluate (vue.runtime.esm.js?ff9b:2984)
    at VueComponent.computedGetter [as $pending] (vue.runtime.esm.js?ff9b:3261)
```
...tough to debug!
What is `__isVuelidateAsyncVm`, what does it mean? 
If I just add `<pre>{{ $v }}</pre>` it trigger the error on a untouched form where the error still don't occur yet.
Thanks for help!
 (sorry very difficult to fiddle this one)

**Comment by Frizi** [comment] 2017-08-30 08:57
Could you show your validation config or ideally create a reproduction on the fiddle? The `__isVuelidateAsyncVm` is an internal property to decide if certain validation is asynchronous. It's an implementation detail and you should not rely on it in any way in your code. Anyhow, it says it's accessed on undefined, which happens here https://github.com/monterail/vuelidate/blob/5e5436455972bd0456b8ae5da001ad8d4ba78e41/src/index.js#L222-L235

This whole method is really a computed value, so it's computed when you access it. Printing `$v` accesses everything, forcing the whole vuelidate model to recompute instantly.

The `run.output` is undefined. That means this code must set it so.
https://github.com/monterail/vuelidate/blob/5e5436455972bd0456b8ae5da001ad8d4ba78e41/src/index.js#L167-L184

It's the output of your validation rule, which returns undefined for some reason.

It is certainly an error of your configuration, though I never specified anywhere that this behaviour (returning undefined) is illegal. I do say that it should be a boolean on a promise though.

I'd like to preserve `undefined` as illegal, but in development mode an error to the console could be reported and the value treated like being valid. That means there is work to do on both ends 😉  On your side, just make sure that your validators doesn't return undefined and you are free to upgrade.

**Comment by gplume** [comment] 2017-08-30 13:46
Hi Frizi, thank you so much for your complete explanation, really thoughtful and detailed as always.
Now I know where to look and I can see the `Promise` culprit you're talking about. A lot of the configuration need API calls to be ready and that's why it would be so difficult to recreate in a fiddle, sorry for that.
I will keep you informed,
Thanks again.

ps: idea:: create a vuelidate api function to activate/deactivate the validation process?

**Comment by gplume** [comment] 2017-08-30 15:35
Great! Got it in 5 minutes this time, thanks very much again!
A custom validator function wasn't returning any bool if `value == null`... classic I guess.

**Comment by Frizi** [comment] 2017-08-31 19:57
@gplume Glad i helped 😄 

I'm not sure if i get your idea for "triggering validation". It possibly might be a bit redundant. The whole library is based on computed properties and those are lazy by default. That means validation process happens only when you look up the validation outcome. To not trigger the process, you have to not read this final state. This reasoning can be a little bit tricky when you add promises to the mix, but it kinda works 😉

If you have something more behind this idea and want to explain it further, please feel free to continue the discussion or even create a separate issue for it. I'm closing this ticket as the original issue was fixed.

**Closed by Frizi** 2017-08-31 19:57 UTC

**Comment by dmig** [comment] 2017-11-20 04:41
@Frizi I just faced this issue and got reproducible case when implemented your advice on server-side validation https://github.com/monterail/vuelidate/issues/216#issuecomment-345510836

```javascript
  data () {
    return {
      login: '',
      password: '',
      validPassword: true
    }
  },
  validations: {
    login: { required },
    password: {
      validPassword: () => this.validPassword
    }
  },
```

This error occurs on component load, because Vuelidate tries to access variable before it was initialized by Vue.
Had to use this workaround:
```javascript
    password: {
      validPassword: () => this.validPassword || true
    }
```

Maybe it's better to initialize validation state after all components mounted?

**Comment by dmig** [comment] 2017-11-20 05:03
Unfortunately this workaround breaks field validation :(
Need to find another solution...

**Comment by Frizi** [comment] 2017-11-21 00:29
@dmig This is a common knowledge in JavaScript. The point of arrow functions is to have lexical `this`. Those functions doesn't have their own context. You have to use object methods for that. Your solution is OK, but it can be even shorter:
```javascript
    password: {
      validPassword () { return this.validPassword }
    }
```

**Comment by dmig** [comment] 2017-11-21 02:31
You should mention this in docs, because it's not obvious that you can't use `this` inside arrow function as validator. I familiar with a-f features, but I expected it to have my component as `this`, not component where `$v` defined.

**Comment by chiptus** [comment] 2019-07-26 07:40
I think it is obvious when you understand arrow functions. However also vuex mentions that if you need `this` you shouldn't use arrow functions, so I guess it won't harm to add that in the docs.

Thanks for a great library!
