### ISSUE TITLE
Validation in Basic example html does not work if removes $v from html and validators does not return to params

### ISSUE THREAD

**Issue by freccon** [monterail/vuelidate#108] opened 2017-03-25 23:50 UTC
In your example https://jsfiddle.net/Frizi/b5v4faqf/ that belongs to a basic example in html, the results of $ params required and minLength are showing as "null" ....

The example shows:

"$params": {
      "required": null,
      "minLength": null
    }

And should show

$params": {
      "required": {
        "type": "required"
      },
      "minLength": {
        "type": "minLength",
        "min": 5
      }
    }

I'm using the same example in an project, if the {{$ v}} is removed form the html validation does not work and "$params" are not displayed correctly , both in my project and jsfiddle.

How can I use a basic example that works as it should?

**Comment by Frizi** [comment] 2017-03-27 00:55
That's probably a bug in browser bundle. I'll have to create an e2e setup to automate testing for that. This should work as expected if you use npm package with webpack or any other bundler.

**Comment by Frizi** [comment] 2017-03-27 09:40
marking as duplicate of #103, please continue discussion there.

**Comment by Frizi** [comment] 2017-03-27 13:27
Wrong, this is actually still failing, but only in browser bundle.

**Comment by Frizi** [comment] 2017-04-06 20:59
Fixed in v0.4.3

**Closed by Frizi** 2017-04-06 20:59 UTC
Labels: bug, web-bundle

**Comment by hong-duc** [comment] 2018-02-10 14:34
I still get
```
"$params": {
"required": null,
"minLength": null
}
```

I am using it in electron

**Comment by guzmo** [comment] 2018-02-23 11:03
Same here, always null objects in $params.

**Comment by RipkensLar** [comment] 2018-11-12 09:22
+1
Using it in an electron environment and since switching the $params are always null.
