### ISSUE TITLE
Validator does not update if $v data is not displayed in html

### ISSUE THREAD

**Issue by Sarpedion** [monterail/vuelidate#105] opened 2017-03-22 21:48 UTC
Greetings,

I've recently updated from version 2.0 to 4.1, and I've noticed that validate states in $v object no longer update as they were before.
After playing around a bit with jsfiddle example, I've noticed that everything works as intened only if {{$v}} is somewhere within template.

jsfiddle to demonstrate the issue can be found [here](https://jsfiddle.net/pdt3kxyf/), notice that {{$v}} is not in template and if you add and then remove value from input, styling will not change. If you add {{$v}} everything works. 

Is this a bug, or is it intented to be so?

**Comment by yageek** [comment] 2017-03-24 09:44
I'm experiencing exactly the same issue with 0.4.1 and vue 2.2.2.

Adding `{{$v}}` within the template solves it but it is ugly workaround.

**Comment by Frizi** [comment] 2017-03-27 09:41
marking as duplicate of #103, please continue discussion there.

**Closed by Frizi** 2017-03-27 09:41 UTC
