### ISSUE TITLE
Validation status is sometimes not evaluated in 0.4.1

### ISSUE THREAD

**Issue by pdanpdan** [monterail/vuelidate#103] opened 2017-03-22 09:53 UTC
https://jsfiddle.net/gLg17z9o/

1.
Try to click Validate => it turns to red.
Now try to fill field - validation stays red.

2.
Fill field => it turns green.
Clear field => it stays green.

3.
Replace <pre>{{$v.form.password.$error}}</pre> with <pre>{{$v.form.password}}</pre>
Now everything works as expected.

**Comment by xereda** [comment] 2017-03-22 12:43
The same happens to me. Note that if you print the validation object on screen, it works. Look at this:

https://jsfiddle.net/xereda/gLg17z9o/1/

**Comment by inanimatt** [comment] 2017-03-22 15:37
Yep, same here. Frustratingly it's a [Heisenbug](https://en.wikipedia.org/wiki/Heisenbug): using the Vue devtools in chrome to debug it makes it act differently.

**Comment by frankdugan3** [comment] 2017-03-22 16:56
I'm experiencing this as well.

**Comment by grucha** [comment] 2017-03-23 12:46
Same here. Only printing particular validation status makes it work.

**Comment by cspeer** [comment] 2017-03-24 13:45
I'm right there with you... @monterail You mind taking a look? I think this is rather critical since it renders the whole plugin useless.

**Comment by ecmel** [comment] 2017-03-24 13:54
Same here only works while devtool is active

**Comment by jonataswalker** [comment] 2017-03-24 13:58
Weird. If you go investigating on devtool, suddenly the validation "wakes up".

**Comment by freccon** [comment] 2017-03-26 00:20
Same here,

I have used a very abrupt and inappropriate temporary solution

`<pre style="display:none">{{$v}}<pre>`

**Comment by korpa** [comment] 2017-03-26 12:10
Hi,

I'm pretty sure, this is not a vuelidate issue, but an iusse in vuejs itself. Please  have a look at: https://jsfiddle.net/ac98frL2/

Try to click on "add field". Nothing will happen. Now change line 6 from ```<!-- {{foo}} -->``` to ```{{foo}}``` and click on "Run" in the top left corner of jsfiddle. Click on "Add field" again => a new field "field2" should appear.
If you click on "Submit", nothing happens. Now change line 8 as well (```{{bar}}}```) and re-run the Jsfiddle. Click on "Add field" and then on "Submit". The background of field2 should be red now.

For me it looks like that vuejs only updates if at least one element bound to a static data variable is updated.
What do you think? Could this be the problem?

**Comment by ScreamZ** [comment] 2017-03-26 12:28
Have something similar in #109... The devtool update but the view don't.... Looks like a vuejs bug any related issue ????

**Comment by Frizi** [comment] 2017-03-27 01:02
Something fishy is going on there. Funny enough, it's hard to test as things get evaluated properly when I'm looking at them with expects. I'll dive into that asap.

**Comment by Frizi** [comment] 2017-03-27 09:38
I'm making this a master bug for this issue. It's duplicated a few times now.

**Comment by ScreamZ** [comment] 2017-03-27 10:05
Ok buddy, take a look at https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats
Should be something like...

Good luck

**Comment by Frizi** [comment] 2017-03-27 12:37
@ScreamZ I'm totally aware of that functionality. The problematic part was my hidden dependency on render function inside validation computed values. The only hacky part of the library actually bitten me. Adding single `depend()` should fix it. Check #113 for details.

**Comment by ScreamZ** [comment] 2017-03-27 13:10
@Frizi Ok, well done! Didn't understood everything but okay :p is that release on NPM ? 0.4.2 ? Thanks

**Comment by Frizi** [comment] 2017-03-27 13:12
Released as v0.4.2. Please test in your setup.

**Comment by inanimatt** [comment] 2017-03-27 13:20
Yep, working for me. Thanks for the quick turnaround!

**Comment by jonataswalker** [comment] 2017-03-27 13:22
Fixed here. Many thanks.

**Comment by Frizi** [comment] 2017-03-27 13:23
https://jsfiddle.net/gLg17z9o/4/
This fiddle also confirms it works. Issue fixed :)

**Closed by Frizi** 2017-03-27 13:23 UTC
Labels: bug

**Comment by ScreamZ** [comment] 2017-03-27 13:25
@Frizi depend() is a method of ? render function of vue ?

**Comment by Frizi** [comment] 2017-03-27 17:02
@ScreamZ That's a method of a Watcher, which triggers the `depend` of all it's Deps. This essentially makes all of the dependencies of given watcher be copied over to current `Dep.target`, which in our case is currently evaluated `computed` value. The `_watcher` i'm `depend`ing on is the one that runs the `render` function of current component's instance. In this case the instance of internal `Validation` vm.

https://github.com/vuejs/vue/blob/dev/src/core/observer/watcher.js#L207
https://github.com/vuejs/vue/blob/dev/src/core/instance/lifecycle.js#L190

**Comment by ScreamZ** [comment] 2017-03-27 18:01
@Frizi Awesome explanation, thanks for this.

**Comment by manniL** [comment] 2018-07-23 10:50
Somehow I can still reproduce this in `v0.7.4`
