### ISSUE TITLE
Collection not required, but if present, subfield required

### ISSUE THREAD

**Issue by Youdaman** [monterail/vuelidate#112] opened 2017-03-27 10:02 UTC
Is it possible to define a rule where a collection is not required, but if it exists (eg a user chooses to add an item to the collection) then subfield(s) are required?

I tried setting up a rule like this but got "TypeError: Cannot convert undefined or null to object" in console when the collection did not exist on certain records.

**Comment by Youdaman** [comment] 2017-03-27 10:05
My way around it was to set minlength to 1 and just include a default item with values "None" for string subfields and 0 for number subfields.

**Comment by Frizi** [comment] 2017-03-27 21:39
You could potentially use a functional `validations` and define the validation for given field only if it's value is nonempty. Something along those lines

``` javascript
validations () {
  const def = {
    alwaysPresentField: { required }
  }

  if (this.myObject) {
    def.myObject = {
      name: { required }
    }
  }

  return def
}
```

**Comment by Youdaman** [comment] 2017-03-28 01:35
Thanks.

When I changed my `validations: {...}` to `validations() { return {...} }` $v became undefined.

I was using version 0.2.0 so I thought maybe it doesn't have dynamic validations so I updated to the latest (version 0.4.2)

However the error I get now is `TypeError: Cannot read property 'proxy' of undefined`

Vuelidate was working fine when it was just an attribute/property instead of a function so I have no idea.

**Comment by Frizi** [comment] 2017-03-28 04:57
That's weird. It's true you have to update it, but the proxy error is not normal. Can you post an example on jsfiddle?

**Comment by Youdaman** [comment] 2017-03-28 05:20
Too tricky to repro on jsfiddle as it's part of an app with lots of moving parts (and I'm guessing it's one of those parts interfering).

My best guess is that it could be caused by me using Firebase, and perhaps the validation creation is kicking in before the data is actually ready, causing it to not create $v -- again this is a wild guess, and you probably already have safeguards/procedures for handling setup of validation for async data yeah?

**Comment by Youdaman** [comment] 2017-04-02 05:48
I found what was causing this error -- turns out it was some of the `$trackBy:` rules.

I commented-out all my trackBy lines which stopped the error, then uncommented them one by one to figure out which ones were causing the problem.

I can't see a pattern/reason as to why some validations can use trackBy while others throw that `proxy` error mentioned above, but if I work it out I'll update this thread.

**Comment by cirinoalejandro** [comment] 2017-04-03 13:52
I'm having the same error: `TypeError: Cannot read property 'proxy' of undefined`
After updating Vuelidate from 0.3.1 to 0.4.2
Using Vue and Nuxt, latest versions.

**Comment by amirrustam** [comment] 2017-04-03 20:00
I'm also getting this error. It's caused by this line: https://github.com/monterail/vuelidate/blob/e60afe4941fe2de3683f2e4173b879fe0ec299e7/src/index.js#L247

**Comment by Frizi** [comment] 2017-04-03 22:13
I'd really like to get my hands on a repro. It has to be testable in the end anyway.
@Youdaman I suspect something like that could happen, thought he "creation of $v" i supposed to be a solved problem as it's created on demand, only in requested parts, as getters are evaluated. Can you check the data re you tracking with `trackBy`? Also the commented out trackers are a very big clue, if you could only extract that from your app.

**Comment by vip30** [comment] 2017-04-11 10:14
I have the same issues too.
I use the vue-router for pushing the route by clicking button and sometime it throw out 
``Cannot read property 'proxy' of undefined``

**Comment by Frizi** [comment] 2017-04-14 07:32
I think there are some funky precise lifecycle stuff going on and a hack biting back. I noticed a reliable way to trigger similar issue is to use a validation state inside a watcher created by `watch` object. I'm in the process of ditching the existing hacks out to make SSR work again, and it potentially can fix this issue too.

**Comment by Youdaman** [comment] 2017-04-14 08:09
Yeah sorry for not coming back with a repro @Frizi but glad others have chimed in.

**Comment by Frizi** [comment] 2017-04-25 21:50
@Youdaman can you please check it in your code against `ssr` branch? I'm planning to release it soon, but first I want to know if it actually fixed the issue (among other ones).

**Comment by Youdaman** [comment] 2017-04-26 01:09
I haven't had the error since, and I'm using `$trackBy: 'index` where `index` is a unique ID I generated for each item in array properties of my data.

My only guess was I was using a field that was either not unique or didn't exist (maybe I had a typo) and the code for `$trackBy` wasn't dealing with that edge case? Sorry I can't confirm/check further but I will let you know if I encounter the issue again! Perhaps @vip30 might be able to test for you.

**Comment by masterix21** [comment] 2017-04-27 16:54
Error "Cannot read property 'proxy' of undefined" seems to be caused by vuex-router-sync in my code. Can confirm it someone?

**Comment by Youdaman** [comment] 2017-04-27 18:04
@masterix21 I don't use vuex-router-sync but I had the error so it might not be specifically that.

**Comment by ssut** [comment] 2017-05-06 11:04
I'm suffering the same issue here saying that "Cannot read property 'proxy' of undefined'", using a boilerplate [vue-webpack-plus](https://github.com/CodinCat/vue-webpack-plus).

**Comment by Kibyra** [comment] 2017-05-08 11:41
I was suffering the same problem ("Cannot read property 'proxy' of undefined") and I agree with @masterix21. If I dont use vue-router-sync there is no problem.

**Comment by creativecoder** [comment] 2017-05-20 04:09
I was also experiencing the error `Cannot read property 'proxy' of undefined` triggered by https://github.com/monterail/vuelidate/blob/e60afe4941fe2de3683f2e4173b879fe0ec299e7/src/index.js#L247. I am *not* using vue-router-sync. I am using nuxt.

Switching to the ssr branch seems to have fixed the issue.

**Comment by Frizi** [comment] 2017-05-20 06:21
@creativecoder that's great news! I'm going to soon work on it a little and release is it as next version.

**Comment by marguskoiduste** [comment] 2017-05-24 12:39
I'm also seeing the `Cannot read property 'proxy' of undefined` error randomly pop up in our production logs after updating to Vuelidate 0.4.2. I haven't been able to reproduce it in development environment.

I'm using vue-router 2.2.0. The error is always triggered after user leaves the route.

Looking forward for the new version! Also it would be good to change the title of the issue or create new issue.

**Comment by Austio** [comment] 2017-05-25 15:14
@Frizi  can confirm that using the SSR branch fixes the proxy issue for me.  On vue 2.3.2

Do you have a timeline for a release for that branch?

**Comment by Frizi** [comment] 2017-05-30 20:12
@Austio I just released that. Closing then. Thanks for confirmation!

**Closed by Frizi** 2017-05-30 20:12 UTC
Labels: bug

**Comment by pohnean** [comment] 2017-08-16 03:28
this really needs a proper fix, a conditional check or at least prevent the 'Cannot convert undefined or null to object' error from happening.

my validators are as such:
```
validations: {
	array1: {
		$each: {
			name: {
				required: required
			},
			array2: {
				$each: {
					name: {
						required: required
					}
				}
			}
		}
	}
},
```
where array2 is an optional collection of each object in array 1
